import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case italian = "it"
    case spanish = "es"
    case chinese = "zh"
    case arabic = "ar"
    
    var id: String { self.rawValue }
    
    var displayName: String {
        switch self {
        case .english: return "English"
        case .italian: return "Italiano"
        case .spanish: return "Español"
        case .chinese: return "中文"
        case .arabic: return "العربية"
        }
    }
}

extension String {
    func localized(for languageCode: String) -> String {
        guard let langDict = translations[languageCode],
              let translated = langDict[self] else {
            return self // Fallback to English (the key itself)
        }
        return translated
    }
}

private let translations: [String: [String: String]] = [
    "it": [
        "Track your sleep pattern and wake up refreshed.": "Monitora il tuo sonno e svegliati riposato.",
        "Get Started": "Inizia ora",
        "By continuing, you agree to Ninety's \n**Terms of Service** and **Privacy Policy.**": "Continuando, accetti i **Termini di Servizio** e l'**Informativa sulla Privacy** di Ninety.",
        "Set Wake Time": "Imposta Sveglia",
        "Ninety": "Ninety",
        "Next Up": "Prossima Sveglia",
        "Alarm On": "Sveglia Attiva",
        "Alarm Off": "Sveglia Disattivata",
        "Settings": "Impostazioni",
        "Sleep History": "Cronologia Sonno",
        "Diagnostics": "Diagnostica",
        "Select": "Seleziona",
        "Done": "Fine",
        "SMART ALARM": "SVEGLIA INTELLIGENTE",
        "Wake Window": "Finestra di Risveglio",
        "Haptic Pre-Alarm": "Pre-Allarme Aptico",
        "APPEARANCE": "ASPETTO",
        "Automatic": "Automatico",
        "PERMISSIONS": "PERMESSI",
        "Notifications": "Notifiche",
        "Apple Health": "Salute",
        "GENERAL": "GENERALE",
        "LANGUAGE": "LINGUA",
        "Language": "Lingua",
        "About Ninety": "Informazioni su Ninety",
        "Smart sleep tracking powered by on-device ML. Your data stays on your devices.": "Perfeziona il tuo riposo con Ninety. Grazie all'apprendimento automatico avanzato eseguito direttamente sul dispositivo, analizziamo i tuoi cicli di sonno da 90 minuti per individuare l'istante perfetto per il risveglio. La tua privacy è fondamentale: ogni calcolo avviene localmente, garantendo che i tuoi dati non lascino mai il tuo dispositivo.",
        "Version": "Versione",
        "Light": "Chiaro",
        "Night": "Notte",
        "System": "Sistema",
        "Pick your days": "Scegli i giorni",
        "Today": "Oggi",
        "Tomorrow": "Domani",
        "No days selected": "Nessun giorno selezionato",
        "Updating Plan...": "Aggiornamento in corso...",
        "Choose Days to Plan": "Scegli i giorni per pianificare",
        "Not started yet": "Non ancora avviato",
        "Open the Watch app to finish setting up": "Apri l'app sull'Apple Watch per completare la configurazione",
        "Tracking in progress": "Monitoraggio in corso",
        "Wake-up delivered": "Risveglio completato",
        "No alarms configured.": "Nessuna sveglia configurata.",
        "Ready": "Pronto",
        "Scheduled": "Programmata",
        "Wake-up triggered": "Sveglia innescata",
        "Waiting for 10 epochs": "In attesa di 10 epoche",
        "No 30-second epoch yet": "Nessuna epoca da 30s ancora",
        "No features computed yet": "Caratteristiche non ancora calcolate",
        "Wake": "Veglia",
        "NREM": "NREM",
        "REM": "REM",
        "Your Session": "La tua sessione",
        "Status": "Stato",
        "Watch Connectivity": "Connettività Watch",
        "Sleep Classifier": "Classificatore Sonno",
        "AlarmKit Constraints": "Vincoli AlarmKit",
        "Log Stream": "Flusso di Log",
        "Starts Tracking:": "Inizio Monitoraggio:",
        "Wake-Up Alarm:": "Allarme Risveglio:",
        "Sleep Stage:": "Fase del Sonno:",
        "Watch:": "Watch:",
        "Alarm:": "Allarme:",
        "Scheduled For:": "Programmata per:",
        "Last Payload:": "Ultimo Invio:",
        "Watch Session:": "Sessione Watch:",
        "Delivery:": "Consegna:",
        "Model:": "Modello:",
        "Raw Stage:": "Fase Raw:",
        "Official Stage:": "Fase Ufficiale:",
        "Epoch:": "Epoca:",
        "Features:": "Caratteristiche:",
        "No logs yet. Schedule an alarm to begin.": "Nessun log. Programma una sveglia per iniziare.",
        "Wake up by": "Sveglia entro",
        "Wake-up target": "Orario di risveglio",
        "Tap to adjust your time": "Tocca per regolare l'orario",
        "Set a time for this day": "Imposta un orario per questo giorno",
        "Choose wake-up time": "Scegli l'orario di risveglio",
        "Scroll to set hour and minutes": "Scorri per impostare ore e minuti",
        "Tap to edit": "Tocca per modificare",
        "Alarm off for this day": "Sveglia disattivata per questo giorno",
        "Next": "Avanti",
        "Welcome to Ninety": "Benvenuto in Ninety",
        "Ninety uses on-device machine learning to find the ideal moment to wake you — within the time you set.": "Ninety utilizza il Machine Learning direttamente sul tuo dispositivo per trovare il momento perfetto per svegliarti — entro l'orario che imposti tu.",
        "Set Your Wake Time": "Imposta il tuo orario",
        "Tap the clock to choose when you need to be up. Ninety wakes you at the best point in your sleep cycle.": "Tocca l'orologio per scegliere entro quando vuoi essere svegliato. Ninety ti sveglierà nel momento ideale del tuo ciclo di sonno.",
        "Customize Every Day": "Personalizza ogni giorno",
        "Each day can have its own wake-up time. Tap a day to select it and adjust the schedule.": "Ogni giorno della settimana può avere un orario diverso. Tocca un giorno per selezionarlo e impostare la sua sveglia.",
        "On or Off. Your Call.": "Attiva o disattiva",
        "Toggle the alarm for each day independently — keep your weekdays and weekends perfectly balanced.": "Accendi o spegni la sveglia per ogni singolo giorno in modo indipendente.",
        "Private by Design": "100% sul dispositivo",
        "Your sleep data never leaves your device. No servers, no cloud — everything runs locally on your iPhone.": "I tuoi dati sul sonno non lasciano mai il tuo telefono. Nessun server, nessun cloud — solo tu e il tuo dispositivo.",
        "You're All Set": "Sei pronto!",
        "Everything is set up. Sweet dreams.": "Tutto è configurato. Sogni d'oro!",
        "Replay Tour": "Ripeti il tutorial",
        "Haptic Feedback": "Feedback aptico",
        "Clock Debug Logs": "Log di Debug Orologio",
        "Copy Clock Logs to Clipboard": "Copia i log negli appunti",
        "No clock logs yet.": "Nessun log orologio.",
        "Ninety logo": "Logo Ninety",
        "Opens the main sleep schedule": "Apre la schermata principale del sonno",
        "Permissions are required to schedule your weekly wake-up plan.": "I permessi sono necessari per programmare il piano sveglia settimanale.",
        "Watch unreachable. Request queued (Will fire when Watch wakes).": "Watch non raggiungibile. Richiesta in coda (verrà inviata quando il Watch si risveglia).",
        "Sleep stage model ready": "Modello fasi del sonno pronto",
        "Clear Logs": "Cancella Log",
        "Alarm saved": "Sveglia salvata",
        "Open Watch": "Apri Watch",
        "Tracking": "Monitoraggio",
        "Arm on Apple Watch": "Imposta su Apple Watch",
        "Open Ninety once on your Apple Watch before sleep. No extra tap is needed after that. Tracking starts at %@.": "Apri Ninety una volta sul tuo Apple Watch prima di dormire. Dopo non serve nessun altro tocco. Il monitoraggio inizia alle %@.",
        "Smart Alarm ready": "Smart Alarm pronta",
        "Apple Watch will start sleep tracking at %@.": "Apple Watch inizierà il monitoraggio del sonno alle %@.",
        "Tracking active on Apple Watch": "Monitoraggio attivo su Apple Watch",
        "The sleep window is running on Apple Watch now.": "La finestra di monitoraggio è attiva ora su Apple Watch.",
        "Open Ninety on Apple Watch once before sleep to set Smart Alarm. After that it starts automatically.": "Apri Ninety su Apple Watch una volta prima di dormire per impostare la Smart Alarm. Dopo partirà automaticamente.",
        "Watch queued for:": "Watch in coda per:",
        "Watch ready for:": "Watch pronto per:"
    ],
    "es": [
        "Track your sleep pattern and wake up refreshed.": "Sigue tus horas de sueño y despierta renovado.",
        "Get Started": "Empezar",
        "By continuing, you agree to Ninety's \n**Terms of Service** and **Privacy Policy.**": "Al continuar, aceptas los **Términos de Servicio** y la **Política de Privacidad** de Ninety.",
        "Set Wake Time": "Ajustar Alarma",
        "Ninety": "Ninety",
        "Next Up": "Próximo",
        "Alarm On": "Alarma Activa",
        "Alarm Off": "Alarma Inactiva",
        "Settings": "Ajustes",
        "Sleep History": "Historial de Sueño",
        "Diagnostics": "Diagnóstico",
        "Select": "Seleccionar",
        "Done": "Aceptar",
        "SMART ALARM": "ALARMA INTELIGENTE",
        "Wake Window": "Ventana de Despertar",
        "Haptic Pre-Alarm": "Pre-alarma Háptica",
        "APPEARANCE": "APARIENCIA",
        "Automatic": "Automático",
        "PERMISSIONS": "PERMISOS",
        "Notifications": "Notificaciones",
        "Apple Health": "Salud",
        "GENERAL": "GENERAL",
        "LANGUAGE": "IDIOMA",
        "Language": "Idioma",
        "About Ninety": "Acerca de Ninety",
        "Smart sleep tracking powered by on-device ML. Your data stays on your devices.": "Domina tu descanso con Ninety. Mediante el aprendizaje automático avanzado en el dispositivo, analizamos tus ciclos de sueño de 90 minutos para encontrar el momento perfecto para despertar. Tu privacidad es lo primero: cada cálculo se realiza localmente, garantizando que tus datos nunca salgan de tu dispositivo.",
        "Version": "Versión",
        "Light": "Claro",
        "Night": "Noche",
        "System": "Sistema",
        "Pick your days": "Elige tus días",
        "Today": "Hoy",
        "Tomorrow": "Mañana",
        "No days selected": "No hay días seleccionados",
        "Updating Plan...": "Actualizando plan...",
        "Choose Days to Plan": "Elige los días para el plan",
        "Not started yet": "No iniciado",
        "Open the Watch app to finish setting up": "Abre la app en el Watch para completar",
        "Tracking in progress": "Monitoreo en curso",
        "Wake-up delivered": "Despertar completado",
        "No alarms configured.": "Sin alarmas configuradas.",
        "Ready": "Listo",
        "Scheduled": "Programada",
        "Wake-up triggered": "Alarma activada",
        "Waiting for 10 epochs": "Esperando 10 épocas",
        "No 30-second epoch yet": "Sin épocas de 30s",
        "No features computed yet": "Sin datos calculados",
        "Wake": "Despierto",
        "NREM": "NREM",
        "REM": "REM",
        "Your Session": "Tu Sesión",
        "Status": "Estado",
        "Watch Connectivity": "Conexión del Watch",
        "Sleep Classifier": "Clasificador de Sueño",
        "AlarmKit Constraints": "Restricciones AlarmKit",
        "Log Stream": "Registro de eventos",
        "Starts Tracking:": "Inicia Monitoreo:",
        "Wake-Up Alarm:": "Alarma de Despertar:",
        "Sleep Stage:": "Fase de Sueño:",
        "Watch:": "Watch:",
        "Alarm:": "Alarma:",
        "Scheduled For:": "Programada para:",
        "Last Payload:": "Último envío:",
        "Watch Session:": "Sesión de Watch:",
        "Delivery:": "Entrega:",
        "Model:": "Modelo:",
        "Raw Stage:": "Fase Raw:",
        "Official Stage:": "Fase Oficial:",
        "Epoch:": "Época:",
        "Features:": "Datos:",
        "No logs yet. Schedule an alarm to begin.": "Sin registros. Programa una alarma para empezar.",
        "Wake up by": "Despertar antes de",
        "Wake-up target": "Hora objetivo",
        "Tap to adjust your time": "Toca para ajustar la hora",
        "Set a time for this day": "Configura una hora para este dia",
        "Choose wake-up time": "Elige la hora de despertar",
        "Scroll to set hour and minutes": "Desliza para elegir hora y minutos",
        "Tap to edit": "Toca para editar",
        "Alarm off for this day": "Alarma desactivada para este dia",
        "Next": "Siguiente",
        "Welcome to Ninety": "Bienvenido a Ninety",
        "Ninety uses on-device machine learning to find the ideal moment to wake you — within the time you set.": "Ninety usa Machine Learning directamente en tu dispositivo para encontrar el momento perfecto para despertarte — dentro del horario que elijas.",
        "Set Your Wake Time": "Configura tu hora",
        "Tap the clock to choose when you need to be up. Ninety wakes you at the best point in your sleep cycle.": "Toca el reloj para elegir la hora límite para despertar. Ninety te despertará en el momento ideal de tu ciclo de sueño.",
        "Customize Every Day": "Personaliza cada día",
        "Each day can have its own wake-up time. Tap a day to select it and adjust the schedule.": "Cada día de la semana puede tener un horario diferente. Toca un día para seleccionarlo y configurar su alarma.",
        "On or Off. Your Call.": "Activa o desactiva",
        "Toggle the alarm for each day independently — keep your weekdays and weekends perfectly balanced.": "Enciende o apaga la alarma para cada día de forma independiente.",
        "Private by Design": "100% en el dispositivo",
        "Your sleep data never leaves your device. No servers, no cloud — everything runs locally on your iPhone.": "Tus datos de sueño nunca salen de tu teléfono. Sin servidores, sin nube — solo tú y tu dispositivo.",
        "You're All Set": "¡Listo!",
        "Everything is set up. Sweet dreams.": "Todo está configurado. ¡Dulces sueños!",
        "Replay Tour": "Repetir tutorial",
        "Haptic Feedback": "Retroalimentación háptica",
        "Clock Debug Logs": "Registros de reloj",
        "Copy Clock Logs to Clipboard": "Copiar registros al portapapeles",
        "No clock logs yet.": "Sin registros de reloj.",
        "Ninety logo": "Logo Ninety",
        "Opens the main sleep schedule": "Abre la programación principal de sueño",
        "Permissions are required to schedule your weekly wake-up plan.": "Se requieren permisos para programar tu plan semanal de despertar.",
        "Watch unreachable. Request queued (Will fire when Watch wakes).": "Watch inaccesible. Solicitud en cola (se enviará cuando el Watch despierte).",
        "Sleep stage model ready": "Modelo de fases del sueño listo",
        "Clear Logs": "Borrar registros",
        "Alarm saved": "Alarma guardada",
        "Open Watch": "Abrir Watch",
        "Tracking": "Seguimiento",
        "Epoch Processing": "Procesamiento de Época",
        "No processed epoch yet.": "Aún no hay una época procesada.",
        "Time": "Hora",
        "HR mean": "HR media",
        "Motion mean": "Motion media",
        "Timestamp:": "Hora:",
        "HR mean:": "HR media:",
        "HR std:": "HR desv std:",
        "HR range:": "HR rango:",
        "Motion mean:": "Motion media:",
        "Motion max:": "Motion max:",
        "Motion jerk:": "Motion jerk:"
    ],
    "zh": [
        "Track your sleep pattern and wake up refreshed.": "追踪您的睡眠模式，焕发活力地醒来。",
        "Get Started": "开始使用",
        "By continuing, you agree to Ninety's \n**Terms of Service** and **Privacy Policy.**": "继续即表示您同意 Ninety 的 **服务条款** 和 **隐私政策**。",
        "Set Wake Time": "设置唤醒时间",
        "Ninety": "Ninety",
        "Next Up": "下一场闹钟",
        "Alarm On": "闹钟开启",
        "Alarm Off": "闹钟关闭",
        "Settings": "设置",
        "Sleep History": "睡眠历史",
        "Diagnostics": "诊断",
        "Select": "选择",
        "Done": "完成",
        "SMART ALARM": "智能闹钟",
        "Wake Window": "唤醒窗口",
        "Haptic Pre-Alarm": "触觉预告闹钟",
        "APPEARANCE": "外观",
        "Automatic": "自动",
        "PERMISSIONS": "权限",
        "Notifications": "通知",
        "Apple Health": "Apple 健康",
        "GENERAL": "常规",
        "LANGUAGE": "语言",
        "Language": "语言",
        "About Ninety": "关于 Ninety",
        "Smart sleep tracking powered by on-device ML. Your data stays on your devices.": "开启高效睡眠。Ninety 利用先进的端侧机器学习技术，精准分析 90 分钟睡眠周期，为您捕捉最佳苏醒时刻。隐私至上：所有计算均在本地完成，确保您的数据永不出境。",
        "Version": "版本",
        "Light": "浅色",
        "Night": "深色",
        "System": "系统",
        "Pick your days": "选择您的日期",
        "Today": "今天",
        "Tomorrow": "明天",
        "No days selected": "未选择日期",
        "Updating Plan...": "正在更新计划...",
        "Choose Days to Plan": "选择日期以排期",
        "Not started yet": "尚未开始",
        "Open the Watch app to finish setting up": "打开 Watch 应用完成设置",
        "Tracking in progress": "正在追踪",
        "Wake-up delivered": "已送达唤醒",
        "No alarms configured.": "未配置闹钟。",
        "Ready": "准备就绪",
        "Scheduled": "已排期",
        "Wake-up triggered": "闹钟已触发",
        "Waiting for 10 epochs": "等待 10 个周期",
        "No 30-second epoch yet": "尚无 30 秒周期",
        "No features computed yet": "尚无计算特征",
        "Wake": "清醒",
        "NREM": "非快速眼动",
        "REM": "快速眼动",
        "Your Session": "您的会话",
        "Status": "状态",
        "Watch Connectivity": "Watch 连接",
        "Sleep Classifier": "睡眠分类器",
        "AlarmKit Constraints": "AlarmKit 限制",
        "Log Stream": "日志流",
        "Starts Tracking:": "开始追踪：",
        "Wake-Up Alarm:": "唤醒闹钟：",
        "Sleep Stage:": "睡眠阶段：",
        "Watch:": "Watch：",
        "Alarm:": "闹钟：",
        "Scheduled For:": "排期于：",
        "Last Payload:": "末次载荷：",
        "Watch Session:": "Watch 会话：",
        "Delivery:": "送达状态：",
        "Model:": "模型：",
        "Raw Stage:": "原始阶段：",
        "Official Stage:": "官方阶段：",
        "Epoch:": "周期：",
        "Features:": "特征：",
        "No logs yet. Schedule an alarm to begin.": "暂无日志。请先设置闹钟开始。",
        "Wake up by": "在此时间前唤醒",
        "Next": "下一步",
        "Welcome to Ninety": "欢迎使用 Ninety",
        "Ninety uses on-device machine learning to find the ideal moment to wake you — within the time you set.": "Ninety 使用设备端机器学习，在您设定的时间内找到最佳唤醒时刻。",
        "Set Your Wake Time": "设置您的时间",
        "Tap the clock to choose when you need to be up. Ninety wakes you at the best point in your sleep cycle.": "点击时钟选择最晚唤醒时间。Ninety 会在您睡眠周期的理想时刻唤醒您。",
        "Customize Every Day": "自定义每一天",
        "Each day can have its own wake-up time. Tap a day to select it and adjust the schedule.": "每天可以设置不同的唤醒时间。点击某天来选择并设置闹钟。",
        "On or Off. Your Call.": "开启或关闭",
        "Toggle the alarm for each day independently — keep your weekdays and weekends perfectly balanced.": "独立开关每一天的闹钟。",
        "Private by Design": "100% 本地运行",
        "Your sleep data never leaves your device. No servers, no cloud — everything runs locally on your iPhone.": "您的睡眠数据永远不会离开手机。没有服务器、没有云端——只有您和您的设备。",
        "You're All Set": "准备就绪！",
        "Everything is set up. Sweet dreams.": "一切已配置完成。祝您好梦！",
        "Replay Tour": "重播教程",
        "Haptic Feedback": "触觉反馈",
        "Clock Debug Logs": "时钟调试日志",
        "Copy Clock Logs to Clipboard": "复制时钟日志到剪贴板",
        "No clock logs yet.": "暂无时钟日志。",
        "Ninety logo": "Ninety 标志",
        "Opens the main sleep schedule": "打开主睡眠日程",
        "Permissions are required to schedule your weekly wake-up plan.": "需要权限来安排您的每周唤醒计划。",
        "Watch unreachable. Request queued (Will fire when Watch wakes).": "Watch 不可达。请求已排队（Watch 唤醒后将发送）。",
        "Sleep stage model ready": "睡眠阶段模型已就绪",
        "Clear Logs": "清除日志",
        "Alarm saved": "闹钟已保存",
        "Open Watch": "打开 Watch",
        "Tracking": "追踪",
        "Epoch Processing": "周期处理",
        "No processed epoch yet.": "还没有处理过的周期。",
        "Time": "时间",
        "HR mean": "心率均值",
        "Motion mean": "运动均值",
        "Timestamp:": "时间：",
        "HR mean:": "心率均值：",
        "HR std:": "心率标准差：",
        "HR range:": "心率范围：",
        "Motion mean:": "运动均值：",
        "Motion max:": "运动最大值：",
        "Motion jerk:": "运动突变量："
    ],
    "ar": [
        "Track your sleep pattern and wake up refreshed.": "تتبع أنماط نومك واستيقظ منتعشاً.",
        "Get Started": "ابدأ الآن",
        "By continuing, you agree to Ninety's \n**Terms of Service** and **Privacy Policy.**": "بالاستمرار، فإنك توافق على **شروط الخدمة** و**سياسة الخصوصية** الخاصة بـ Ninety.",
        "Set Wake Time": "تعيين وقت الاستيقاظ",
        "Ninety": "Ninety",
        "Next Up": "المنبه القادم",
        "Alarm On": "المنبه مفعّل",
        "Alarm Off": "المنبه معطل",
        "Settings": "الإعدادات",
        "Sleep History": "سجل النوم",
        "Diagnostics": "التشخيصات",
        "Select": "تحديد",
        "Done": "تم",
        "SMART ALARM": "المنبه الذكي",
        "Wake Window": "نافذة الاستيقاظ",
        "Haptic Pre-Alarm": "تنبيه لمسي مسبق",
        "APPEARANCE": "المظهر",
        "Automatic": "تلقائي",
        "PERMISSIONS": "الأذونات",
        "Notifications": "الإشعارات",
        "Apple Health": "صحة Apple",
        "GENERAL": "عام",
        "LANGUAGE": "اللغة",
        "Language": "اللغة",
        "About Ninety": "حول Ninety",
        "Smart sleep tracking powered by on-device ML. Your data stays on your devices.": "أتقن فن الراحة مع Ninety. باستخدام تقنيات تعلم الآلة المتقدمة مباشرة على جهازك، نقوم بتحليل دورات نومك البالغة 90 دقيقة لتحديد اللحظة المثالية لاستيقاظك. خصوصيتك هي أولويتنا: تتم كل عملية حسابية محلياً، مما يضمن عدم خروج بياناتك أبداً من جهازك.",
        "Version": "الإصدار",
        "Light": "فاتح",
        "Night": "ليلي",
        "System": "النظام",
        "Pick your days": "اختر أيامك",
        "Today": "اليوم",
        "Tomorrow": "غداً",
        "No days selected": "لم يتم اختيار أيام",
        "Updating Plan...": "جاري تحديث الخطة...",
        "Choose Days to Plan": "اختر أياماً للجدولة",
        "Not started yet": "لم يبدأ بعد",
        "Open the Watch app to finish setting up": "افتح تطبيق الساعة لإكمال الإعداد",
        "Tracking in progress": "تتبع جارٍ",
        "Wake-up delivered": "تم الاستيقاظ",
        "No alarms configured.": "لا توجد منبهات معدة.",
        "Ready": "جاهز",
        "Scheduled": "مجدول",
        "Wake-up triggered": "تم إطلاق المنبه",
        "Waiting for 10 epochs": "بانتظار 10 دورات",
        "No 30-second epoch yet": "لا توجد دورة 30 ثانية بعد",
        "No features computed yet": "لم يتم احتساب ميزات بعد",
        "Wake": "مستيقظ",
        "NREM": "NREM",
        "REM": "REM",
        "Your Session": "جلستك",
        "Status": "الحالة",
        "Watch Connectivity": "اتصال الساعة",
        "Sleep Classifier": "مصنف النوم",
        "AlarmKit Constraints": "قيود AlarmKit",
        "Log Stream": "تدفق السجل",
        "Starts Tracking:": "بدء التتبع:",
        "Wake-Up Alarm:": "منبه الاستيقاظ:",
        "Sleep Stage:": "مرحلة النوم:",
        "Watch:": "الساعة:",
        "Alarm:": "المنبه:",
        "Scheduled For:": "مجدول لـ:",
        "Last Payload:": "آخر حمولة:",
        "Watch Session:": "جلسة الساعة:",
        "Delivery:": "التسليم:",
        "Model:": "النموذج:",
        "Raw Stage:": "المرحلة الخام:",
        "Official Stage:": "المرحلة الرسمية:",
        "Epoch:": "الدورة:",
        "Features:": "الميزات:",
        "No logs yet. Schedule an alarm to begin.": "لا توجد سجلات بعد. قم بجدولة منبه للبدء.",
        "Wake up by": "الاستيقاظ قبل",
        "Next": "التالي",
        "Welcome to Ninety": "مرحباً بك في Ninety",
        "Ninety uses on-device machine learning to find the ideal moment to wake you — within the time you set.": "يستخدم Ninety تعلم الآلة مباشرة على جهازك للعثور على اللحظة المثالية لإيقاظك — ضمن الوقت الذي تحدده.",
        "Set Your Wake Time": "اضبط وقتك",
        "Tap the clock to choose when you need to be up. Ninety wakes you at the best point in your sleep cycle.": "اضغط على الساعة لاختيار الوقت الأقصى للاستيقاظ. سيوقظك Ninety في اللحظة المثالية من دورة نومك.",
        "Customize Every Day": "خصّص كل يوم",
        "Each day can have its own wake-up time. Tap a day to select it and adjust the schedule.": "يمكن لكل يوم من أيام الأسبوع أن يكون له وقت مختلف. اضغط على يوم لتحديده وضبط منبهه.",
        "On or Off. Your Call.": "تفعيل أو تعطيل",
        "Toggle the alarm for each day independently — keep your weekdays and weekends perfectly balanced.": "قم بتشغيل أو إيقاف المنبه لكل يوم بشكل مستقل.",
        "Private by Design": "100% على الجهاز",
        "Your sleep data never leaves your device. No servers, no cloud — everything runs locally on your iPhone.": "بيانات نومك لا تغادر هاتفك أبداً. لا خوادم، لا سحابة — أنت وجهازك فقط.",
        "You're All Set": "أنت جاهز!",
        "Everything is set up. Sweet dreams.": "كل شيء مُعدّ. أحلام سعيدة!",
        "Replay Tour": "إعادة الجولة",
        "Haptic Feedback": "ردود فعل لمسية",
        "Clock Debug Logs": "سجلات تصحيح الساعة",
        "Copy Clock Logs to Clipboard": "نسخ سجلات الساعة إلى الحافظة",
        "No clock logs yet.": "لا توجد سجلات ساعة بعد.",
        "Ninety logo": "شعار Ninety",
        "Opens the main sleep schedule": "يفتح جدول النوم الرئيسي",
        "Permissions are required to schedule your weekly wake-up plan.": "الأذونات مطلوبة لجدولة خطة الاستيقاظ الأسبوعية.",
        "Watch unreachable. Request queued (Will fire when Watch wakes).": "الساعة غير قابلة للوصول. تم وضع الطلب في الانتظار.",
        "Sleep stage model ready": "نموذج مراحل النوم جاهز",
        "Clear Logs": "مسح السجلات",
        "Alarm saved": "تم حفظ المنبه",
        "Open Watch": "افتح Watch",
        "Tracking": "التتبع",
        "Epoch Processing": "معالجة الدورة",
        "No processed epoch yet.": "لا توجد دورة معالجة بعد.",
        "Time": "الوقت",
        "HR mean": "متوسط HR",
        "Motion mean": "متوسط الحركة",
        "Timestamp:": "الوقت:",
        "HR mean:": "متوسط HR:",
        "HR std:": "الانحراف المعياري HR:",
        "HR range:": "نطاق HR:",
        "Motion mean:": "متوسط الحركة:",
        "Motion max:": "أقصى حركة:",
        "Motion jerk:": "تغيّر الحركة:"
    ]
]
